version: "3.8"
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=kubsu
      - POSTGRES_PASSWORD=kubsu
      - POSTGRES_DATABASE=kubsu
        #      volumes:
        # - ./postgres:/docker-entrypoint-initdb.d
    networks:
      - mynetwork
  pythonapp:
    image: pythonapp:latest
    build: ./python_app
    ports:
      - 8000:8047
    environment:
      - DATABASE_URL=postgresql+psycopg://kubsu:kubsu@db:5432/kubsu
    depends_on:
      - db
    networks:
      - mynetwork

volumes:
  postgres:

networks:
  mynetwork:
